# Generated by Django 5.2.5 on 2026-05-18 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ba7ce586-73d0-43b9-baa5-4aa4293b9711'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('descriptions', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='000000', max_length=7)),
                ('secondary_color', models.CharField(default='FFFFFF', max_length=7)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
    ]
