# Generated by Django 5.2.5 on 2026-05-19 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharptest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6826f159-f2de-4778-9259-b6f077eb4da2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6826f159-f2de-4778-9259-b6f077eb4da2'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='sharptest.brand')),
            ],
            options={
                'db_table': 'service_categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
